using UnityEngine;

public class BounceImage : MonoBehaviour
{
    public float amplitude = 1f;         // ’µ‚Ë‚ÌU•
    public float frequency = 1f;         // ’µ‚Ë‚Ìü”g”

    private Vector3 initialPosition;     // ‰ŠúˆÊ’u

    private void Start()
    {
        // ‰ŠúˆÊ’u‚ğ•Û‘¶‚·‚é
        initialPosition = transform.position;
    }

    private void Update()
    {

        // Œ»İ‚ÌŠÔ‚É‰‚¶‚Ä‰æ‘œ‚ğ’µ‚Ë‚³‚¹‚é
        float newY = initialPosition.y + Mathf.Sin(Time.time * frequency) * amplitude;
        transform.position = new Vector3(transform.position.x, newY, transform.position.z);
    }
}
